version: "3.3"
services:
  web:
    restart: unless-stopped
    build: .
    pull_policy: build
    # ports:
    #   - 8000:80
    volumes:
      - ./app:/app

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wa-mb-http.rule=Host(`mb.wa.dtcloud.cz`)"
      - "traefik.http.routers.wa-mb-http.entrypoints=web"
      - "traefik.http.routers.wa-mb-http.middlewares=wa-mb-redirect-https@docker"

      - "traefik.http.middlewares.wa-mb-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wa-mb-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wa-mb-https.rule=Host(`mb.wa.dtcloud.cz`)"
      - "traefik.http.routers.wa-mb-https.entrypoints=websecure"
      - "traefik.http.routers.wa-mb-https.tls=true"
      - "traefik.http.routers.wa-mb-https.tls.certresolver=letsencrypt"

  static:
    image: nginx:alpine
    restart: unless-stopped

    volumes:
      - ./app/static:/usr/share/nginx/html/static:ro

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wa-mb-static-http.rule=Host(`mb.wa.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wa-mb-static-http.entrypoints=web"
      - "traefik.http.routers.wa-mb-static-http.middlewares=wa-mb-static-redirect-https@docker"

      - "traefik.http.middlewares.wa-mb-static-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wa-mb-static-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wa-mb-static-https.rule=Host(`mb.wa.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wa-mb-static-https.entrypoints=websecure"
      - "traefik.http.routers.wa-mb-static-https.tls=true"
      - "traefik.http.routers.wa-mb-static-https.tls.certresolver=letsencrypt"
networks:
  default:
    name: gateway
    external: true